include "plugin/define/orxPlugin_CoreID.e"

public enum type orxPLUGIN_FUNCTION_BASE_ID_RENDER

 orxPLUGIN_FUNCTION_BASE_ID_RENDER_INIT = 0,
  orxPLUGIN_FUNCTION_BASE_ID_RENDER_EXIT,
  orxPLUGIN_FUNCTION_BASE_ID_RENDER_GET_WORLD_POSITION,
  orxPLUGIN_FUNCTION_BASE_ID_RENDER_GET_SCREEN_POSITION,

  orxPLUGIN_FUNCTION_BASE_ID_RENDER_NUMBER,

  orxPLUGIN_FUNCTION_BASE_ID_RENDER_NONE = 0xFFFFFFFF
	
end type
­12.53