public enum type orxPLUGIN_CORE_ID

 orxPLUGIN_CORE_ID_DISPLAY = 0,
 orxPLUGIN_CORE_ID_JOYSTICK,
 orxPLUGIN_CORE_ID_KEYBOARD,
 orxPLUGIN_CORE_ID_MOUSE,
 orxPLUGIN_CORE_ID_PHYSICS,
 orxPLUGIN_CORE_ID_RENDER,
 orxPLUGIN_CORE_ID_SOUNDSYSTEM,
 orxPLUGIN_CORE_ID_NUMBER,
 orxPLUGIN_CORE_ID_NONE = 0xFFFFFFFF
	
end type
­11.36