
public include "plugin/define/orxPlugin_CoreID.e"

public enum type orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK

	orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK_INIT = 0,
	orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK_EXIT,

	orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK_GET_AXIS_VALUE,
	orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK_IS_BUTTON_PRESSED,
	orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK_IS_CONNECTED,

	orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK_NUMBER,

	orxPLUGIN_FUNCTION_BASE_ID_JOYSTICK_NONE = 0xFFFFFFFF

end type
­14.55